### ISSUE TITLE
Error: Invalid Origin

### ISSUE THREAD

**Issue by ethanent** [devsnek/discord-rich-presence#10]
Here's a screenshot with error details:

![image](https://user-images.githubusercontent.com/14060354/46910667-f9090b00-cefc-11e8-8efd-6a56f65df2d5.png)

I'm not sure exactly what the cause is, but it seems to be something wrong with the HTTP `Origin` header sent by `ws`. I know that `ws` provides a way to change the sent `Origin` header.

Anyway, this could either be a significant issue or something wrong on my end. :)

**Comment by kairusds** [comment]
the docs says it doesn't work on browser, maybe it has something to do with that?

**Comment by ethanent** [comment]
@kairusds Interesting theory. I was using it in an Electron BrowserWindow through `require()` at time, so I'm not sure. It is possible that the library may have some not-fully-functional fallback to detect the fact that it's in a browser environment and attempt to use frontend JS WebSockets.

**Comment by devsnek** [comment]
the library treats electron renderer as a browser, on purpose. you should run it in the app process instead.
