### ISSUE TITLE
Socket opens, instantly closes, Promise Rejection

### ISSUE THREAD

**Issue by Superleximus** [devsnek/discord-rich-presence#14]
Every single time I attempt to use my program, I get this: 

`(node:2077) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unhandled "error" event. ([object Object])`

Discord's console shows this: 

`[RPCServer:IPC] Socket Opened: 56
[RPCServer:IPC] Socket Close: 56`

Any ideas?

**Comment by devsnek** [comment]
@Superleximus please attach an error listener: `client.on('error', console.error)`

**Comment by devsnek** [comment]
@Superleximus please try `npm i devsnek/discord-rich-presence` and then test again.

**Comment by Superleximus** [comment]
that fixed it, i feel stupid now.
