### ISSUE TITLE
Npm stuck when installing

### ISSUE THREAD

**Issue by lMartin3** [devsnek/discord-rich-presence#16]
When I try to install discord-rich-presence with npm it gets stuck.
>npm install discord-rich-presence
[..................] \ fetchMetadata: sill resolveWithNewModule discord-rpc@3.0.1 checking installable status

**Comment by devsnek** [comment]
so open a bug report with npm

**Comment by lMartin3** [comment]
This happens only with this package

**Comment by AngryKiller** [comment]
Delete the npm cache
