### ISSUE TITLE
Error while executing: undefined ls-remote -h -t ssh://git@github.com/discordjs/rpc.git

### ISSUE THREAD

**Issue by SlayTheVirus** [devsnek/discord-rich-presence#18]
I got this error while running 'npm i discord-rich-presence':

> npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/rpc.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Edit: Here is my log file. https://pastebin.com/XbtBqekZ

**Comment by AngryKiller** [comment]
Well the error clearly states it's related to npm itself so you should post an issue on their GitHub instead 😉

**Comment by SlayTheVirus** [comment]
Oh wow, that was dumb of me lol
