### ISSUE TITLE
Function to close a Discord RPC connection?

### ISSUE THREAD

**Issue by AngryKiller** [devsnek/discord-rich-presence#2]
So that it disappears from the profile

**Comment by devsnek** [comment]
call *disconnect*

**Comment by AngryKiller** [comment]
It's not working

**Comment by armaldio** [comment]
@devsnek Can confirm, socket is actually closed but Rich Presence still show, even after a long time
What to do to stop the rich presence ?

**Comment by devsnek** [comment]
discord will continue tracking your application's process even when you disconnect. that's outside of my control. you can manually clear your presence before disconnecting.
