### ISSUE TITLE
Could not connect Node.JS

### ISSUE THREAD

**Issue by loockeeer** [devsnek/discord-rich-presence#28]
Hi ! I was planning to use it in some Node.JS project, but when I tested it, I had this strange error : 
```
Error: Could not connect
```

It's strange because first I have discord installed and running on my computer, and then, I never had this issue before :thinking: 
My computer is running on Manjaro Linux with i3wm as a window manager but I don't think that could lead to this issue...

(My code, pretty simple) 
```js
const client = require('discord-rich-presence')('443366917483266059');
 
client.updatePresence({
  state: 'slithering',
  details: '🐍',
  startTimestamp: Date.now(),
  endTimestamp: Date.now() + 1337,
  instance: true,
});
```

**Comment by Ximaz** [comment]
Same.

**Comment by DylanD16** [comment]
Run client.setActivity instead.

**Comment by loockeeer** [comment]
Thanks !
