### ISSUE TITLE
getting http status codes of 101.

### ISSUE THREAD

**Issue by harborseals** [devsnek/discord-rich-presence#29]
i get the error of Uncaught (in promise) Error: connection closed.

I did some digging, and its apparently switching protocols?

For context, i'm using a require statement to run the code. I'm running this in a chromium browser using electron for my web application. I'd assume it would just run normally, but no. 

If the issue is electron, what should I do?
![fat error](https://user-images.githubusercontent.com/70864817/103977822-aa7c6280-513f-11eb-9d15-1547ad54d724.png)
![why are you switching protocols](https://user-images.githubusercontent.com/70864817/103977828-ad775300-513f-11eb-987a-47f8cc15d477.png)

**Comment by devsnek** [comment]
RPC in browser uses websockets. The connection is likely being closed because you are not whitelisted by discord to use RPC via websockets.
