### ISSUE TITLE
Closing Discord, unhandled promise rejection

### ISSUE THREAD

**Issue by xL0b0** [devsnek/discord-rich-presence#30]
If closing Discord, this ends up in an unhandled promise rejection. Could this please be changed so it could be handled, in order to retry initializing it after it was closed?

**Comment by Sv443** [comment]
Try listening for the `error` event like this:  
```js
const client = require('discord-rich-presence')('180984871685062656');

client.on('error', err => {
    console.log(`Error: ${err}`);
});
```

**Comment by xL0b0** [comment]
This can only account for errors in the init. Otherwise you will still get 

`(node:16829) UnhandledPromiseRejectionWarning: Error: connection closed`

if you close Discord while running.
