### ISSUE TITLE
Might be dumb question, but how to turn off presence? 

### ISSUE THREAD

**Issue by justiceserv** [devsnek/discord-rich-presence#33]
I need to turn off presence when a certain action is given, and I cannot use .disconnect() because I need to make presence available again when action is triggered. Is there any way I can turn off presence without disconnecting? Plus, is there any button support for this wrapper? Thanks!

**Comment by Nano-AI** [comment]
#12

**Comment by Nano-AI** [comment]
`client.disconnect()` should work.

**Comment by devsnek** [comment]
You can create a new client instance after disconnecting. This also does support buttons.
